# Site settings
name: Vison's Blog
email: sen_wei@163.com
author: WeiSen
url: http://vison123.github.io
resume_site: http://vison123.github.io
github: https://github.com/vison123/
baseurl: ""
description: Actually, less is more!
meta_description: 为森;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: vison123
highlighter: rouge

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : vison
    disqus :
        short_name : vison
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light